apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nestjs-serverless
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: nestjs-app:v1  # Imagem da aplicação NestJS
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
