apiVersion: apps/v1 # Versão da API do Kubernetes para Deployments
kind: Deployment # Tipo do recurso - um Deployment gerencia ReplicaSets
metadata: # Metadados do Deployment
  name: nestjs-deployment # Nome do Deployment
  labels: # Labels para identificação
    app: nestjs-deployment
spec: # Especificações do Deployment
  replicas: 1 # Número de réplicas (pods) desejadas
  selector: # Seletor para identificar os pods gerenciados
    matchLabels:
      app: nestjs-deployment
  template: # Template para criação dos pods          
    metadata: # Metadados dos pods
      labels: # Labels dos pods
        app: nestjs-deployment
    spec: # Especificações dos pods
      containers: # Lista de containers no pod
      - name: nestjs-app # Nome do container
        image: nestjs-app:v1 # Imagem do container a ser utilizada
        imagePullPolicy: Never # Política de pull da imagem
        ports:
        - containerPort: 3000 # Porta do container        