apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  labels:
    app: nestjs-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: nestjs-deployment
  template:
    metadata:
      labels:
        app: nestjs-deployment
    spec:
      containers:
      - name: nestjs-app
        image: 10.2.1.125:30676/nestjs-app:v1  # 🔥 Caminho correto do registry
        imagePullPolicy: Never  # Use IfNotPresent se quiser permitir updates
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "500m"             
            memory: "300Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
