apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  namespace: default
  labels:
    app: nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-deployment
  template:
    metadata:
      labels:
        app: nestjs-deployment
    spec:  # ESTE SPEC ESTÁ FALTANDO NO SEU ARQUIVO!
      containers:
        - name: nestjs-app
          image: 10.2.1.125:30676/nestjs-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "300Mi"
