apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
  labels:
    app: nestjs-deployment
spec:
  replicas: 1  # O HPA irá aumentar isso automaticamente
  selector:
    matchLabels:
      app: nestjs-deployment
  template:
    metadata:
      labels:
        app: nestjs-deployment
    spec:
      containers:
      - name: nestjs-app
        image: nestjs-app:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "200m"  # 200 milicores (0.2 vCPU) - Necessário para o HPA funcionar
            memory: "256Mi"  # Boa prática definir também a memória
          limits:
            cpu: "500m"  # 500 milicores (0.5 vCPU) - Define um limite seguro
            memory: "512Mi"
